"""add usermixin to user class

Revision ID: 4e13fd611d17
Revises: b38f0d19c35a
Create Date: 2022-04-17 19:31:49.055490

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "4e13fd611d17"
down_revision = "b38f0d19c35a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user", sa.Column("password_hash", sa.String(length=150), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "password_hash")
    # ### end Alembic commands ###
